### ISSUE TITLE
Milestone 1: Beta release

### ISSUE THREAD

**Issue by dabbott** [noya-app/noya#1]
### App

- [x] Keymap
- [x] Undo
- [x] Groups
- [x] Asset collections
- [x] Shared styles
- [x] Symbols (@milg15)
- [x] Quick measure
- [x] Smart snap (@leannepepper)
- [x] Export image/vector files (@dabbott)
- [x] Import image/vector files (@dabbott)
- Masking
  - [x] Clipping masks
  - [x] Alpha masks
- [x] Copy & paste

### Layer list

- [x] Drag n drop
- [x] Context menu
- [x] Rename layer
- [x] Filter layers

### Inspector

- Layout
  - [x] Constrain proportions
  - [x] Mirror v|h
  - [x] Rotation
  - [x] Scaling
  - [x] #276
- [x] Arrange/distribute
- [x] Opacity
- [x] Blur
- [x] Text styles
- [x] Toggle visibility
- [x] #279

### Tools

- [x] Text (@dabbott)
  - [ ] Text layer layout
- [ ] Pen tool
- [x] Slice tool
- [x] Other shapes
  - [x] Line
  - [x] Triangle
  - [x] Star
  - [x] Polygon

### Canvas

- [x] Zoom
  - [x] Use zoom when rendering editor UI (e.g. drag handles)
- [x] Trackpad gestures (@souporserious)
- [x] Shadows
- [x] Inner Shadows
- [x] Drag elements
- [x] Marquee selection
- [x] Boolean operations
- [x] #291
- [x] Context menu
- [x] Image fill

### File

- [x] File > New
- [x] File > Open
- [x] File > Save
- [x] #249
- [x] #250

### Desktop app

- [ ] #70

---

### Inspector

- [x] #211
  
### Canvas

- Groups
  - [x] Shadows
- Border radius
  - [ ] Handle individual points with custom radius
  - [ ] Determine maximum radius per point (a function of the angle?)
- Image Layers
  - [x] Borders
  - [x] Shadows
  - [x] #251
  - [x] Blur
  - [x] Color adjust
- Drag handles
  - [x] Should resize layers in groups
- Smart snap
  - [x] Inserting new layer
  - [x] Scaling
  - [ ] Point editing mode
