### ISSUE TITLE
UX review checklist for beta

### ISSUE THREAD

**Issue by dchen** [noya-app/noya#241]
This is a collection of issues discovered while walking through the user experience in preparation for a beta release. It will be updated as more issues are encountered.

## Missing Functionality
- [ ] Locking a layer does not function, or its functionality is unclear.

## Interface
- [ ] Menu and Insert buttons don't have an active state to give feedback that it has been clicked, which makes it feel less responsive.
- [ ] Layers in the layer list don't have an active state to give feedback that it has been clicked, which makes it feel less responsive.
- [ ] Edit Path button has a focus state, which is unusual. For example, select a shape and then click and drag off of the Edit Path button. It will have a purple outline. Is this intended for accessibility/keyboard navigation?
- [ ] You can't toggle the lock layer or layer visibility icon off then on then off. After one cycle, the icon disappears unless you move cursor away and back. 
- [ ] Keyboard shortcuts are missing or not labeled, especially clipboard shortcuts are important. There do seem to be some keyboard shortcuts, such as for zooming in and out, but these are not listed anywhere.
- [ ] Right clicking in certain areas, such as the layer list and menu bar brings up the browser context menu, which is inconsistent as in other areas, it brings up the Noya context menu.

## Accessibility
- [ ] Lock layer and layer visibility icons do not have alt text.
